"""
report_pdf.py
-------------
NEW FILE — save as backend/app/report_pdf.py

Builds the downloadable PDF entirely in the backend (reportlab), replacing
the old call into ml/predict.py's write_pdf_report(). ml/ is still never
touched — this is a backend-only module.

What changed vs. the old one-liner PDF:
  - Branded header (ArbudaScan + tagline)
  - Scan ID printed on the report
  - A "Findings / Impression / Recommendations" section: uses the
    AI-generated report text if one exists for this scan, otherwise a
    rule-based fallback paragraph (so the PDF is never just an image +
    one line, even before anyone clicks "Generate report")
  - A disclaimer footer on every page
"""
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.pdfbase.pdfmetrics import stringWidth

APP_NAME = "ArbudaScan"
APP_TAGLINE = "AI-Assisted Brain Tumor Detection & Analysis"
DISCLAIMER = (
    "Generated by an automated detection system. This is not a medical diagnosis — "
    "all findings must be reviewed and confirmed by a qualified radiologist."
)


def _wrap(text: str, font: str, size: float, max_width: float) -> list[str]:
    words = text.split()
    lines, current = [], ""
    for w in words:
        trial = f"{current} {w}".strip()
        if stringWidth(trial, font, size) <= max_width:
            current = trial
        else:
            if current:
                lines.append(current)
            current = w
    if current:
        lines.append(current)
    return lines


def _fallback_findings(summary: dict) -> str:
    n = summary["num_detections"]
    area = summary["total_tumor_area_pct"]
    if n == 0:
        return (
            "Findings:\nNo regions above the confidence threshold were detected in this slice.\n\n"
            "Impression:\nNo suspicious findings flagged by the automated model on this image.\n\n"
            "Recommendations:\nNo action indicated from this scan alone; continue routine "
            "clinical correlation as appropriate."
        )
    confs = [d["confidence"] for d in summary["detections"]]
    return (
        f"Findings:\nThe model flagged {n} region(s) of interest covering approximately "
        f"{area}% of the image, with confidence scores ranging from {min(confs):.2f} to "
        f"{max(confs):.2f}.\n\n"
        "Impression:\nThe detected region(s) are consistent with a possible abnormality on "
        "this slice; automated detection alone cannot characterize tumor type or grade.\n\n"
        "Recommendations:\nCorrelate with clinical history and additional imaging planes. "
        "Findings should be reviewed by a qualified radiologist before any clinical decision is made."
    )


def _footer(c: canvas.Canvas, width: float, page_num: int):
    c.setFont("Helvetica-Oblique", 7)
    y = 1.4 * cm
    for line in _wrap(DISCLAIMER, "Helvetica-Oblique", 7, width - 4 * cm):
        c.drawString(2 * cm, y, line)
        y -= 0.3 * cm
    c.drawRightString(width - 2 * cm, 1.4 * cm, f"Page {page_num}")


def render_pdf(
    summary: dict,
    annotated_image_path: Path,
    out_path: Path,
    detection_id: int | None = None,
    ai_report: str | None = None,
) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    width, height = A4
    c = canvas.Canvas(str(out_path), pagesize=A4)
    page_num = 1
    y = height - 2 * cm

    c.setFont("Helvetica-Bold", 18)
    c.drawString(2 * cm, y, APP_NAME)
    y -= 0.65 * cm
    c.setFont("Helvetica", 10)
    c.drawString(2 * cm, y, APP_TAGLINE)
    y -= 0.9 * cm

    c.setFont("Helvetica-Bold", 13)
    c.drawString(2 * cm, y, "Brain Tumor Detection Report")
    y -= 0.8 * cm

    c.setFont("Helvetica", 9)
    meta_lines = [
        f"Scan ID: #{detection_id}" if detection_id is not None else None,
        f"Image: {Path(summary['image']).name}",
        f"Generated: {summary['timestamp_utc']}",
        f"Tumor detected: {'YES' if summary['tumor_detected'] else 'NO'}",
        f"Detections: {summary['num_detections']}    Total tumor area: {summary['total_tumor_area_pct']}% of image",
    ]
    for line in meta_lines:
        if line:
            c.drawString(2 * cm, y, line)
            y -= 0.45 * cm
    y -= 0.3 * cm

    try:
        img_w = 10 * cm
        img_h = img_w * summary["image_size"]["height"] / summary["image_size"]["width"]
        c.drawImage(str(annotated_image_path), 2 * cm, y - img_h, width=img_w, height=img_h)
        y -= img_h + 0.9 * cm
    except Exception:
        pass

    c.setFont("Helvetica-Bold", 11)
    c.drawString(2 * cm, y, "Detections")
    y -= 0.55 * cm
    c.setFont("Helvetica", 9)
    if not summary["detections"]:
        c.drawString(2 * cm, y, "(none above the confidence threshold)")
        y -= 0.45 * cm
    for i, d in enumerate(summary["detections"], start=1):
        line = (f"{i}. {d['class_name']}  conf={d['confidence']}  "
                f"bbox={d['bbox_xyxy']}  area={d['area_pct_of_image']}%")
        c.drawString(2 * cm, y, line)
        y -= 0.42 * cm
        if y < 3.5 * cm:
            _footer(c, width, page_num)
            c.showPage()
            page_num += 1
            y = height - 2 * cm
            c.setFont("Helvetica", 9)
    y -= 0.4 * cm

    c.setFont("Helvetica-Bold", 11)
    c.drawString(2 * cm, y, "AI Findings & Recommendations")
    y -= 0.55 * cm
    c.setFont("Helvetica", 9)
    body_text = ai_report.strip() if ai_report else _fallback_findings(summary)
    for paragraph in body_text.split("\n"):
        if not paragraph.strip():
            y -= 0.25 * cm
            continue
        for line in _wrap(paragraph, "Helvetica", 9, width - 4 * cm) or [""]:
            c.drawString(2 * cm, y, line)
            y -= 0.4 * cm
            if y < 3.5 * cm:
                _footer(c, width, page_num)
                c.showPage()
                page_num += 1
                y = height - 2 * cm
                c.setFont("Helvetica", 9)

    _footer(c, width, page_num)
    c.showPage()
    c.save()
    return out_path
